version: "3.7"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "5000:5000"
    hostname: client
    expose:
      - "5000"
    restart: unless-stopped

  sonarqube:
    image: bitnami/sonarqube:latest
    container_name: sonarqube
    ports:
      - "9005:9000"
    expose:
      - 9005
    depends_on:
      - postgresql
    networks:
      - sonarnet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
    volumes:
      - "sonarqube_data:/bitnami/sonarqube"

  postgresql:
    user: root
    image: docker.io/bitnami/postgresql:13
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
