version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "5000:5000"
    hostname: client
    expose:
      - "5000"
    networks:
      - linkednetwork
    restart: unless-stopped

  jenkins:
    image: jenkinsci/blueocean
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - linkednetwork

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    expose:
      - 9000
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
      - sonar.jdbc.username=sonarqube
      - sonar.jdbc.password=xxx
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
  linkednetwork:

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
