version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "5000:5000"
    hostname: client
    expose:
      - "5000"
    networks:
      - linkednetwork
    restart: unless-stopped

  jenkins:
    image: jenkinsci/blueocean
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - linkednetwork

  sonarqube:
    image: sonarqube:8.2-community
    container_name: sonarqube
    ports:
      - "9005:9000"
    expose:
      - 9005
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  sonarnet:
    driver: bridge
  linkednetwork:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
